### ISSUE TITLE
StatusView not working

### ISSUE THREAD

**Issue by durini309** [iammert/StatusView#2]
Hey, I'm not able to use _iammert.com.library.StatusView_ on my App. Everytime I try to run my app, it fails. The error is: 

> android.view.InflateException: Binary XML file line #34: Error inflating class iammert.com.library.StatusView

My code in my XML file is:
<RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/frameContent"
        android:layout_marginTop="?attr/actionBarSize"/>

        <iammert.com.library.StatusView
            android:layout_alignParentBottom="true"
            android:id="@+id/status"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:dismissOnComplete="true"
            app:complete="@layout/sv_layout_complete"
            app:error="@layout/sv_layout_error"
            app:loading="@layout/state_loading"/>
    </RelativeLayout>

For each layout, I have this (same for all)
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/color_bg_success"
    android:gravity="center">

    <ImageView
        android:layout_marginLeft="-16dp"
        android:id="@+id/iconSuccess"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:layout_centerVertical="true"
        android:src="@drawable/ic_check_circle_white_24dp" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:layout_marginLeft="16dp"
        android:layout_toRightOf="@+id/iconSuccess"
        android:gravity="center_vertical"
        android:text="@string/connected_text"
        android:textColor="@color/color_white" />

</RelativeLayout>
```

If I use _ConnectionStatusView_ it works fine... 

Thanks!

**Comment by iammert** [comment]
Hi, I just fixed that. You can use version 1.3. I updated readme file. @durini309
