### ISSUE TITLE
how can i modify your layout text

### ISSUE THREAD

**Issue by wying111** [iammert/StatusView#3]
If I want to download something.for example,I want to show "Loading..." or "Complete" but "conntect" with your layout,how to do? Thanks

**Comment by iammert** [comment]
You can create your own layout for that. It is already mentioned on readme file. You can use StatusView for that. @WangChangQin 
```
<iammert.com.library.StatusView
        android:id="@+id/status"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        app:dismissOnComplete="true"
        app:complete="@layout/completeLayout"
        app:error="@layout/errorLayout"
        app:loading="@layout/loadingLayout"/>
```
